use_frameworks!
platform :ios, '8.0'

target 'ZCWTool_Example' do
  pod 'ZCWTool', :path => '../'

  target 'ZCWTool_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
